[project]
name = "ckanext-switzerland_users"
version = "0.0.1"
dynamic = ["optional-dependencies"]
description = "User Management for opendata.swiss"
authors = [
    {name = "Liip AG", email = "ogdch@liip.ch"}
]
maintainers = [
    {name = "Liip AG", email = "ogdch@liip.ch"}
]
license = {text = "AGPL"}
classifiers = [
    "Intended Audience :: Developers",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
keywords = [
    "CKAN",
    "users",
]

[project.urls]
Documentation = "https://github.com/opendata-swiss/ckanext-switzerland_users"
Repository = "https://github.com/opendata-swiss/ckanext-switzerland_users"
Issues = "https://github.com/opendata-swiss/ckanext-switzerland_users/issues"

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
optional-dependencies = {dev = { file = ["dev-requirements.txt"] }}

[tool.isort]
profile = "black"

[project.entry-points."ckan.plugins"]
ogdch_users = "ckanext.switzerland_users.plugin:OgdchUsersPlugin"
