[options]
packages = find:
namespace_packages = ckanext
install_requires =
include_package_data = True

[options.entry_points]
babel.extractors =
    ckan = ckan.lib.extract:extract_ckan

[flake8]
exclude = ckan,setup.py
max-complexity = 10

[extract_messages]
keywords = translate isPlural
add_comments = TRANSLATORS:
output_file = ckanext/switzerland_users/i18n/ckanext-switzerland_users.pot
width = 80

[init_catalog]
domain = ckanext-switzerland_users
input_file = ckanext/switzerland_users/i18n/ckanext-switzerland_users.pot
output_dir = ckanext/switzerland_users/i18n

[update_catalog]
domain = ckanext-switzerland_users
input_file = ckanext/switzerland_users/i18n/ckanext-switzerland_users.pot
output_dir = ckanext/switzerland_users/i18n

[compile_catalog]
domain = ckanext-switzerland_users
directory = ckanext/switzerland_users/i18n
statistics = true
